### ISSUE TITLE
Does it support volume rendering?

### ISSUE THREAD

**Issue by Shomnipotence** [steaklive/EveryRay-Rendering-Engine#55]
like open vdb or raw

**Comment by steaklive** [comment]
@Shomnipotence no, this project is game dev oriented and, thus, does not support anything you mentioned. 

However, there is support for real-time voxelization (probably not the fastest way to do it) the mesh geometry using a vertex->geometry->pixel shaders pipeline. This was done as a part of the "Voxel Cone Tracing Global Illumination" functionality. You can check "content/shaders/Voxelization.hlsl" for that.

In addition, there is support for "Voxel volumetric fog"
