### ISSUE TITLE
Move dependencies binary files from `bin/x64/` to their respective folder in `external/`

### ISSUE THREAD

**Issue by adriengivry** [steaklive/EveryRay-Rendering-Engine#83]
### User Problem
A bunch of `.dll` files are currently stored in the `bin/x64/`  folder, which should strictly be reserved for compilation output.

### Proposed Solution
We should consider moving these `.dll` files from `bin/x64/` to their respective folder in `external/`.
`bin/` should also be excluded from versioning by adding it to the `.gitignore`.

### Notes
It might be necessary to add a post-build event to copy external libraries `.dll` files to the output folder.

**Comment by steaklive** [comment]
I think the original idea was to include bin/ with .dll files into the repo so that the user could run something without compiling at all. Perhaps I will clean this up once I make automated builds for this repo.

**Comment by adriengivry** [comment]
I think including a pre-compiled binary is a great idea, but it shouldn't be versioned with each commit, but should probably be made into a release for each stable version you want to publish. Most people on GitHub look for releases when they don't want to compile something anyway

**Comment by steaklive** [comment]
done under 1ab446d853726bc8956e89a539d1227456633ddf , 13d5f0900873491a9794b6ca048552efceffa43b
